@startuml
class Hotel {
  +Name
  +Location
  +Rooms_List

  +hotelsearch()
  +reservationcreation()
  +roomaddition()
  +roomremoval()
  +view_all_reservations()
}

class Room {
  +Room_Number
  +Price_Per_Night

  +roomavailability()
}

class Customer {
  +Name
  +Email_Address
  +Phone_Number

  +accountregistration()
  +accountlogin()
  +accountlogout()
  +hotelsearch()
  +reservationcreation()
  +view_booking_history()
}

class Reservation {
  +Reserved_Room
  +Customer_Details
  +Reservation_Dates

  +reservation_Status(Pending, Confirmed, Cancelled)
  +paymentinitiation()
  +reservationcancellation()
  +check_room_availability(Room: Room, Dates: DateRange)
  +view_reservation_details()
}

class Payment {
  +Amount paid
  +Date of payment

  +paymentprocessing()
}

class Admin {
  +paymentmanagement()
  +customeraccountmanagement()
  +login()
  +logout()
}

class Manager {
  +reservationhandling()
  +roommanagement()
  +reportgeneration()
  +complainthandling()
  +notificationsending()
  +reservationupdate()
}

class SearchCriteria {
  +Location
  +Check_In_Date
  +Check_Out_Date
  +Number_of_Guests
}

class DateRange {
  +Start_Date
  +End_Date
}

class Report {
  +Content
  +generate_report()
}

enum ReservationStatus {
  Pending
  Confirmed
  Cancelled
}

Admin --> Hotel
Hotel --> Room
Customer --> Reservation
Reservation --> Room
Reservation --> Customer
Reservation --> Payment
Reservation --> DateRange
Reservation --> ReservationStatus
Admin --> Payment
Admin --> Customer
Admin --> Manager
Manager --> Hotel
Manager --> Reservation
Manager --> Report
Manager --> Customer
Manager --> Payment
Customer --> Payment
Customer --> SearchCriteria
Customer --> Report
Hotel --> SearchCriteria
@enduml