@startuml
class Hotel {
  +Name
  +Location
  +Rooms_List

  +Hotel Search()
  +Reservation Creation()
  +Room Addition()
  +Room Removal()
  +View_All_Reservations()
}

class Room {
  +Room_Number
  +Price_Per_Night

  +Room Availability()
}

class Customer {
  +Name
  +Email_Address
  +Phone_Number

  +Account Registration()
  +Account Login()
  +Account Logout()
  +Hotel Search()
  +Reservation Creation()
  +View_Booking_History()
}

class Reservation {
  +Reserved_Room
  +Customer_Details
  +Reservation_Dates
  +Reservation_Status(Pending, Confirmed, Cancelled)

  +Payment Initiation()
  +Reservation Cancellation()
  +Check_Room_Availability(Room: Room, Dates: DateRange)
  +View_Reservation_Details()
}

class Payment {
  +Amount paid
  +Date of payment

  +Payment Processing()
}

class Admin {
  +Payment Management()
  +Customer Account Management()
  +Login()
  +Logout()
}

class Manager {
  +Reservation Handling()
  +Room Management()
  +Report Generation()
  +Complaint Handling()
  +Notification Sending()
  +Reservation Update()
}

class SearchCriteria {
  +Location
  +Check_In_Date
  +Check_Out_Date
  +Number_of_Guests
}

class DateRange {
  +Start_Date
  +End_Date
}

class Report {
  +Content
  +Generate_Report()
}

enum ReservationStatus {
  Pending
  Confirmed
  Cancelled
}

Admin --> Hotel
Hotel --> Room
Customer --> Reservation
Reservation --> Room
Reservation --> Customer
Reservation --> Payment
Reservation --> DateRange
Reservation --> ReservationStatus
Admin --> Payment
Admin --> Customer
Admin --> Manager
Manager --> Hotel
Manager --> Reservation
Manager --> Report
Manager --> Customer
Manager --> Payment
Customer --> Payment
Customer --> SearchCriteria
Customer --> Report
Hotel --> SearchCriteria
@enduml
