@startuml
actor Customer
participant "Hotel Database" as DB
participant "Hotel Manager" as Manager
participant "Admin" as Admin

Customer -> Admin: Account Registration
Admin -> Customer: Registration Success

Customer -> Admin: Account Login
Admin -> Customer: Login Success

Customer -> DB: Hotel Search
DB -> Customer: List of Hotels

Customer -> DB: Hotel Selection
Customer -> Manager: Reservation Request
Manager -> DB: Reservation Creation
Manager -> DB: Reservation details
DB -> Customer: Display Reservation Details

Customer -> Admin: Payment Initiation
Admin -> DB: Payment Confirmation
DB -> Customer: Display Confirmation

Customer -> Admin: Account Logout
Admin -> Customer: Logout Success
@enduml
