# Generated by Django 4.1.13 on 2024-08-17 16:15

from django.db import migrations, models
import djongo.models.fields
import reservations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('rooms', djongo.models.fields.ArrayField(model_container=reservations.models.Room)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('room_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
