# Generated by Django 4.1.13 on 2024-08-17 16:17

from django.db import migrations
import djongo.models.fields
import reservations.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_hotel_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rooms',
            field=djongo.models.fields.ArrayField(model_container=reservations.models.Room),
        ),
    ]
